### ISSUE TITLE
NeuroCAUSAL -  an platform for storage, sharing, synthesis & meta-analysis of clinical data

### ISSUE THREAD

**Issue by vborghe** [ohbm/hackathon2022#35]
### Title

NeuroCAUSAL - Development of an Open Source Platform for the Storage, Sharing, Synthesis and Meta-Analysis of Clinical Data

### Short description and the goals for the OHBM BrainHack

We wish to work with clinicians, neuroimagers, and software developers to develop an open source platform for the storage, sharing, synthesis and meta-analysis of human clinical data to the service of the clinical and cognitive neuroscience community so that the future of neuropsychology can be transdiagnostic, open, and FAIR.

Following the steps of what enable similar transition in functional neuroimaging, we are breaking down the over-ambitious goal in two stages:

- create a sort of spin-off of [Neuroquery](https://neuroquery.org/) that only covers lesion-related data hence allowing causal inferences 

- A [Neurovault](https://neurovault.org/) kind of tool facilitating sharing of clinical data, which shall benefit from a sort of “neuropsyhcological BIDS formatting guidelines” (OHBM poster #2066 seems to have read our minds)  

### Project lead

Isil Bilgin @complexbrains time zone: GMT+1  - discord: _TBD_
Pedro Pinheiro-Chagas @pinheirochagas time zone: PDT  - discord: _TBD_
Valentina Borghesani @vborghe time zone: EDT  - discord: _TBD_
Sladjana Lukic @Sladja13 time zone: EDT  - discord: **vborghesani** 

### Main Hub

Americas

### Other Hub covered by the leaders

- [ ] Glasgow
- [ ] Asia / Pacific
- [X] Europe / Middle East / Africa
- [ ] Americas

### Link to the Project

https://github.com/neurocausal

### Image for the OHBM brainhack website

https://neurocausal.github.io/images/author/inverted-logo_huf11703388d6cc09ec62cec26261f7e3e_54804_148x148_fit_box_2.png

### Skills

We are very heterogeneous in our own skills sets & levels and welcome all sorts of contributions 😄 

The **ontological issues** we are facing require familiarity with neurology (https://github.com/neurocausal/neurocausal/issues/4) and/or cognitive science (https://github.com/neurocausal/neurocausal/issues/5). These are contentious matters in the field and a perfect solution is not realistic: we seek the good compromise that will make this platform a useful tool for the broad community interested in the future of neuropsychology. 

The **technical issues** will benefit from people familiar with tools to  (e.g., https://github.com/neurocausal/neurocausal_data/issues/1). 

We are aware we just started scratching the surface and will need lots of help on all fronts 🙏  

### Recommended tutorials for new contributors

- [ ] [Set up a brainhack friendly computing environment](https://psy6983.brainhackmtl.org/modules/installation/)
- [ ] [A introduction to Bash](https://psy6983.brainhackmtl.org/modules/introduction_to_terminal/)
- [X] [Python: Writing a script](https://psy6983.brainhackmtl.org/modules/python_scripts/)
- [X] [Python: Data analysis with Python](https://psy6983.brainhackmtl.org/modules/python_data_analysis/)
- [X] [Python: Visualisation](https://psy6983.brainhackmtl.org/modules/python_visualization/)
- [X] [Machine learning basics](https://psy6983.brainhackmtl.org/modules/machine_learning_basics/)
- [X] [BIDS](https://psy6983.brainhackmtl.org/modules/bids/)
- [X] [Machine learning for neuroimaging](https://psy6983.brainhackmtl.org/modules/machine_learning_neuroimaging/)
- [X] [VCS: Using Git and Github](https://psy6983.brainhackmtl.org/modules/git_github/)
- [ ] [VCS: Data management with Datalad](https://psy6983.brainhackmtl.org/modules/datalad/)
- [ ] [Virtualization](https://psy6983.brainhackmtl.org/modules/containers/)
- [ ] High Performance Computing: [Oracle cloud resource](https://brainhack.org/brainhack_cloud/)

### Twitter summary

Towards a transdiagnostic, open, and FAIR neuropsychology? Sounds interesting? Join @ppinheirochagas @complexbrains @NoLaB_Lukic @vborghesani in building https://neurocausal.github.io #OHBMHackathon #Brainhack #OHBM2022

### Short name for the Discord chat channel (~15 chars)

neurocausal

### Please read and follow the OHBM Code of Conduct

- [X] I agree to follow the OHBM Code of Conduct during the hackathon

**Comment by djarecka** [comment]
@vborghe - thanks for testing

@anibalsolon - what should I do now?

**Comment by djarecka** [comment]
btw. i changed slightly the template that it's clear that we want Hub next to a leader names

**Comment by anibalsolon** [comment]
@djarecka now, after we review the info in the issue, the label 'Hacktrack: Good to go' must be added!

**Comment by djarecka** [comment]
oh, ok, so the label is the key! What happen if the author wants to update something later?

**Comment by anibalsolon** [comment]
The issue can be edited, and the CI will be triggered. So the trigger is "issue created or edited" and will only consider issues with the label Good to go.

**Comment by vborghe** [comment]
We can't wait! [here](https://docs.google.com/presentation/d/1jUMNjSsjG-25JGaYiKqC1siwH7Ofxht6Td3LML9Nnvw/edit?usp=sharing) is our slide, with 1 animation. If you have to remove it please let us know and we will provide a static version. Thanks!

**Comment by vborghe** [comment]
@djarecka could you confirm whether the shared slide (with animations) is OK? I can provide a static one and/or in any other format - how are they going to be displayed? Thanks!!
